[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[context.production.environment]
  TWILIO_ACCOUNT_SID = "$TWILIO_ACCOUNT_SID"
  TWILIO_AUTH_TOKEN = "$TWILIO_AUTH_TOKEN"
  TWILIO_PHONE_NUMBER = "$TWILIO_PHONE_NUMBER"

[[redirects]]
  from = "/api/*"
  to = "https://fa-taxi.com/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables will be set in Netlify UI
