[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[context.production.environment]
  # Voeg hier eventuele andere omgevingsvariabelen toe

[[redirects]]
  from = "/api/*"
  to = "https://fa-taxi.com/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables will be set in Netlify UI
